[package]
name = "upload_example"
version = "0.1.0"
edition = "2021"

[dependencies]
s_web = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
mime_guess = "2.0.5"
sanitize-filename = "0.6.0"
