[package]
name = "custom_response_example"
version = "0.1.0"
edition = "2024"

[dependencies]
s_web = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { version = "0.4.42", features = ["serde"] }
